# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

includes:
  platform: src/resources/platform/Taskfile_{{OS}}.yml

vars:
  # app
  APP_NAME: grafana
  BUILD_DIR: build
  S: '{{if eq OS "windows"}}\{{else}}/{{end}}'

  # kubernetes
  KUBERNETES_APP_NAMESPACE: monitoring
  KUBERNETES_MANIFESTS_DIR: '{{.SRC_DIR}}{{.S}}resources{{.S}}kubernetes'
  KUBERNETES_APP_DEPLOYMENT_NAME: deployment.v1.apps/{{.APP_NAME}}--rolling-update
  KUBERNETES_OUTPUT_DIR: '{{.BUILD_DIR}}{{.S}}kubernetes'
  KUBERNETES_INGRESS: '{{.APP_NAME}}.127.0.0.1.nip.io'
  KUBERNETES_CERT: '{{.BUILD_DIR}}{{.S}}certs'

tasks:
  k:fix:
    desc: k8s fix
    cmds:
      - "echo Kubernetes context: $(kubectl config current-context)"
      - task: platform:k:fix

  k:mkdir:
    cmds:
      - "echo OS: {{OS}}, ARCH: {{ARCH}}, CGO_ENABLED: {{.CGO_ENABLED}}"
      - task: platform:k:mkdir

  cert:mkdir:
    cmds:
      - task: platform:cert:mkdir

  k:tls:
    cmds:
      - task: cert:mkdir
      - task: platform:cert:install
      - kubectl create namespace monitoring
      - task: platform:k:tls

  k:repo:
    cmds:
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  k:setup:
    cmds:
      - helm repo update
      - |
        helm install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --create-namespace
      - kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx --timeout=120s
      - |
        helm install metrics-server metrics-server/metrics-server \
          --namespace kube-system \
          --set args={--kubelet-insecure-tls}
      - kubectl rollout status deployment metrics-server -n kube-system --timeout=120s
      - helm install kube-state-metrics prometheus-community/kube-state-metrics -n monitoring
      - kubectl apply -k ./deployment

  k:graph:
    vars:
      KUSTOMIZATION: '{{.KUBERNETES_MANIFESTS_DIR}}{{.S}}overlays{{.S}}local'
      OUTPUT: '{{.KUBERNETES_OUTPUT_DIR}}{{.S}}kustomization.mmd'
    cmds:
      - kubectl graph -k {{.KUSTOMIZATION}} -o mermaid -t 100 > {{.OUTPUT}}

  netrc:
    silent: true
    cmds:
      - go tool sdk-cli netrc

  docker:build:
    silent: true
    vars:
      CICD_TOKEN:
        sh: task netrc
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} . --build-arg=GITLAB_TOKEN={{.CICD_TOKEN}}

  docker:stop:
    silent: true
    cmds:
      - docker stop {{.APP_NAME}}

  docker:delete:
    silent: true
    cmds:
      - docker rm {{.APP_NAME}}

  docker:debug:
    vars:
      DOCKERFILE: '{{.KUBERNETES_MANIFESTS_DIR}}{{.S}}Dockerfile'
    cmds:
      - docker --debug build --secret id=netrc,src={{.HOME}}/.netrc -t {{.DOCKER_IMAGE}} . -f {{.DOCKERFILE}}

  docker:run:
    desc: docker run
    silent: true
    deps: [ docker:build ]
    vars:
      ENV: localstack
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    cmds:
      - task: platform:docker:run

  lint:
    desc: Use golangci-lint (.golangci.yml).
    cmds:
      - go tool golangci-lint run --fix
      - go tool gofumpt -w -l .
      - go tool betteralign -test_files -generated_files -apply ./...

  test:nil:
    cmds:
      - go run go.uber.org/nilaway/cmd/nilaway@latest ./...

  test:race:
    desc: Race conditions check for unit test.
    cmds:
      - go test -race -count 10 ./...

  test:
    cmds:
      - task: test:unit
      - task: test:race
      - task: test:cover

  test:cover:
    cmds:
      - task: platform:test:cover

  test:unit:
    desc: Run unit test.
    cmds:
      - go test ./...

  test:shuffle:
    desc: Run unit test multiple times
    cmds:
      - go run gotest.tools/gotestsum@latest -f testname -- ./... -race -count=15 -shuffle=on

  test:mock:
    desc: Create mocks
    cmds:
      - go tool mockery --config "{{.MOCKERY_CONFIG_DIR}}{{.S}}.mockery.yaml"

  download:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy -v

  upgrade:
    deps: [ download ]
    desc: Check for latest direct dependencies.
    cmds:
      - go-mod-upgrade
      - task: download

  swagger:
    cmds:
      - go get -u github.com/gofiber/swagger
      - go tool swag init -d {{.SWAG_SRC_DIR}} -g {{.ENTRY_POINT}} -o {{.SWAG_OUTPUT_DIR}} --parseGoList --parseDependency

  build:
    desc: 'Build the go exe (output: {{.BIN}})'
    deps: [ download ]
    cmds:
      - "echo OS: {{OS}}, ARCH: {{ARCH}}, CGO_ENABLED: {{.CGO_ENABLED}}"
      - go build -v -ldflags="-s -w" -trimpath -o "{{.BIN}}" "{{.SRC_DIR}}{{.S}}{{.ENTRY_POINT}}"

  size:
    desc: 'Build the go exe (output: {{.BIN}})'
    deps: [ build ]
    cmds:
      - "echo OS: {{OS}}, ARCH: {{ARCH}}, CGO_ENABLED: {{.CGO_ENABLED}}"
      - go run github.com/Zxilly/go-size-analyzer/cmd/gsa@latest "{{.BIN}}"

  start:
    desc: 'runs the main {{.BIN}}'
    aliases:
      - run
    deps: [ build ]
    cmds:
      - task: platform:run

  live:
    cmds:
      - ENV=local APP_NAME=go-api go run github.com/air-verse/air@latest --build.cmd "task build" --build.bin {{.BIN}}

  release:
    desc: Run relevant tasks.
    cmds:
      - task: download
      - task: test:mock
      - task: lint
      - task: swagger
      - task: build
      - task: test

  aws:account:
    silent:
      true
    vars:
      PRODUCT: '{{.CLI_ARGS | default "oms"}}'
      DEV: 178558647998
      UAT: 425981549652
      PRO: 722677935098
    cmds:
      - "echo DEV: arn:aws:iam::178558647998:role/iskaypet-{{.PRODUCT}}-access"
      - "echo UAT: arn:aws:iam::178558647998:role/iskaypet-{{.PRODUCT}}-access"
      - "echo PROD: arn:aws:iam::178558647998:role/iskaypet-{{.PRODUCT}}-access"

  tree:
    silent: true
    cmds:
      - tree -L 3 --dirsfirst --noreport > tree.tmp
      - cat tree.tmp | tr '\302\240' ' ' > tree.log
      - rm -rf tree.tmp

  docker:compose:
    vars:
      CONFIG_FOLDER: src/resources/compose
    cmds:
      - (cd "{{.CONFIG_FOLDER}}" ||exit ; docker-compose down ; docker-compose up --build)

  default:
    cmds:
      - task: release
